# Installed as /etc/systemd/system/klipper.service.d/c5-tunnel.conf
[Unit]
After=c5-tunnel-gadget.service
Wants=c5-tunnel-gadget.service

[Service]
ExecStartPre=-/bin/stty -F /dev/ttyGS0 sane
ExecStartPre=-/bin/stty -F /dev/ttyGS1 sane
ExecStartPre=-/bin/stty -F /dev/ttyGS2 sane
ExecStartPre=-/bin/stty -F /dev/ttyGS3 sane
